apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gemini
  namespace: kagent
spec:
  provider: Gemini
  model: gemini-3.5-flash
  apiKeySecret: gemini-api-key
  apiKeySecretKey: GOOGLE_API_KEY
  gemini: {}